apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-code-with-quarkus-dto6
  namespace: rhn-support-tshearon-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:466740b8b228bcc9e0366efc485df363e79ba602e6db3b7ed5bf55f435ffeaf4
        name: my-java-quarkus
        resources: {}
status: {}
